apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
    tier: db
    project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
      tier: db
      project: roboshop
  template:
    metadata:
      labels:
        app: mongodb
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mongodb
        image: chinna9967/mongodb:1.0.0
        