apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
    tier: app
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogue
      tier: app
      project: roboshop
  template:
    metadata:
      labels:
        app: catalogue
        tier: app
        project: roboshop
    spec:
      containers:
      - name: catalogue
        image: chinna9967/catalogue:1.0.0
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
spec:
  selector:
    app: catalogue
    tier: app
    project: roboshop
  ports:
  - name: catalogue-port
    protocol: TCP
    port: 8080 # this port belongs to service
    targetPort: 8080 # this port belongs to container